# yaml 配置实例
version: '3'
services:
  arex-homepage:
    image: zhangtao25/canyon-homepage:main
    restart: always
    container_name: canyon-homepage
    ports:
      - 8080:8080

  arex-docs:
    image: zhangtao25/canyon-docs:main
    restart: always
    container_name: canyon-docs
    ports:
      - 18888:8080
